openapi: 3.0.0
info:
  title: TableFlow API
  version: 0.1.1
paths:
  /import/{id}:
    get:
      summary: Returns an import.
      parameters:
        - description: Import ID
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
  /import/{id}/download:
    get:
      summary: Downloads the import as a CSV file.
      parameters:
        - description: Import ID
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            text/csv: { }
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
  /import/{id}/rows:
    get:
      summary: Paginate the rows of an import
      parameters:
        - description: Import ID
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
        - description: Pagination offset
          in: query
          name: offset
          schema:
            type: integer
            minimum: 0
        - description: Pagination limit
          in: query
          name: limit
          schema:
            type: integer
            minimum: 0
            maximum: 1000
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
